google_analytics: UA-18418059-2
#theme: jekyll-theme-hacker
remote_theme: pmarsceill/just-the-docs

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-avatar
 - jekyll-include-cache
 
disqus:
    shortname: arvati
