markdown: kramdown # https://kramdown.gettalong.org/converter/html.html
remote_theme: pmarsceill/just-the-docs
title: Crypto-Keys
description: Node Javascript Tool to generate ,encrypt and decrypt RSA and EC keys formated as PEM / DER.
aux_links:
  "Crypto-Keys on GitHub":
    - "//github.com/arvati/crypto-keys"
color_scheme: "dark"


ga_tracking: UA-18418059-2
plugins:
 - jekyll-seo-tag
# - jekyll-feed
# - jekyll-sitemap
# - jekyll-mentions
# - jemoji
# - jekyll-redirect-from
# - jekyll-avatar
# - jekyll-include-cache
 
disqus:
    shortname: arvati
