markdown: kramdown # https://kramdown.gettalong.org/converter/html.html
remote_theme: pmarsceill/just-the-docs


ga_tracking: UA-18418059-2
plugins:
 - jekyll-seo-tag
# - jekyll-feed
# - jekyll-sitemap
# - jekyll-mentions
# - jemoji
# - jekyll-redirect-from
# - jekyll-avatar
# - jekyll-include-cache
 
disqus:
    shortname: arvati
